# Site settings
title: Future, Made by All
email: future.made@offsetmovement.org
url: https://futurema.de
description: "Future, Made by and for all."
keywords: "future, design, coop, software, arts, culture, sustainability"
skills: ""
meta_author: Abbas Tolgay Yilmaz
baseurl: "/future-made-website"



# # Google webmaster tools
# google_verify:

# # https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:


motivations:
  motivations: Motivations

impact: 
  impact: Impact
# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - typeform : add typeform generated contact form

# - comment the line below if you want to stick with the default PHP contact form
contact: typeform

collaborators: 
  collaborators: Collaborators


# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0d0d0d #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Future, Made.
  location: Where are we?
  social: Reach us
  credits: Manifest

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/made_future
  - title: instagram
    url: https://www.instagram.com/the.offset.movement
  - title: github
    url: https://github.com/Future-Made
  
  


# Postal address (add as many lines as necessary)
address:
  - line: Planet
  - line: Earth

# Credits content
credits: 'This project is indeed a <i>movemental one</i>, and we call it <i>"The Offset Movement"</i>. <br><br> Manifest is <a href="https://offsetmovement.org" target="_blank">here.</a> <br><br> Meaning of <strong> "offset" </strong>:  <a href="https://www.merriam-webster.com/thesaurus/offset" target="_blank"><strong> @dictionary</strong></a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

